actions:
- changed-files:
  - any-glob-to-any-file: ['**/action.yml', '**/action.yaml', '.github/**/*']

test:
- changed-files:
  - any-glob-to-any-file: 
    [
      'src/**/*.spec.js',
      'src/**/*.spec.ts',
      'src/**/*.test.js',
      'src/**/*.test.ts',
      'src/**/__tests__/**/*',
      '__tests__/**/*',
      'tests/**/*'
    ]

# Add 'Documentation' label to any changes within 'docs' folder or any subfolders
Documentation:
- changed-files:
  - any-glob-to-any-file: 
    [
      'docs/**/*', 'doc/**/*', 
      'documentation/**/*', 
      '.docs/**/*'
    ]

‚öôÔ∏è configuration:
- changed-files:
  - any-glob-to-any-file:
    [
      '.idea/**/*',
      '.github/**/*',
      '.husky/**/*',
      '.lintstagedrc',
      '.prettierrc',
      '.eslintrc',
      '.editorconfig',
      '.gitignore',
      '.gitattributes',
      '.npmignore',
      '.nvimrc',
      '.npmrc',
      '*.config.js',
      '*.config.ts'
    ]

üì¶ dependencies:
- changed-files: 
  - any-glob-to-any-file: ['package.json', 'package-lock.json', 'yarn.lock', 'pnpm-lock.yaml']
